### ISSUE TITLE
Installer.ps1 attempting to install to multiple directories

### ISSUE THREAD

**Issue by aaroncoville** [jdunkerley/AlteryxFormulaAddOns#31]
In my case - running Alteryx 11.5 - the Installer.ps1 would find both an Admin and a User registry value. The User directory 'HKCU:\SOFTWARE\SRC\Alteryx' did not have an InstallDir64 value, but the script only checks whether the Item Property is returned before assigning the InstallDir64 value into the $bins. This results in the Powershell script attempting to install the files twice, once to 'C:\RuntimeData\FormulaAddIn' which fails (for me).

I fixed this issue by changing line 17 in Installer.ps1 
from: if($reg -ne $null) {
to: if($reg -ne $null -and $reg.InstallDir64 -ne $null) {

I didn't bother with a pull request since its such a minor change and I'm not aware of how pervasive this issue is for other users. 

It should be noted that while the Installer.ps1 will throw an error for the 2nd installation directory the first one (Admin) installs fine and there are no issues.

**Comment by jdunkerley** [comment]
Thanks.
I have added to Installer.
