### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aburnsy** [jdunkerley/AlteryxFormulaAddOns#48]
Hi James/all,

Would you be comfortable applying an open source license to this repo? We would like to make use of this repo, however, we can't do that with a license in place - one of our company's policies. 

This website has decent detail on which license to choose if that is something you are interested in

**Comment by aburnsy** [comment]
choosealicense.com

**Comment by jdunkerley** [comment]
Of course. Will add an MIT license to it.

**Comment by aburnsy** [comment]
Really appreciate that!
